FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY minio /usr/bin/
COPY dockerscripts/docker-entrypoint.sh /usr/bin/

RUN chmod +x /usr/bin/minio && \
    chmod +x /usr/bin/docker-entrypoint.sh

EXPOSE 9000

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

CMD ["minio", "gateway", "s3"]
